apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration
  labels:
    app: collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration
  template:
    metadata:
      labels:
        app: collaboration
    spec:
      containers:
      - name: collaboration
        image: vilasvarghese/collaboration
        ports:
        - containerPort: 8080
        imagePullPolicy: Always